# Generated by Django 3.2.7 on 2021-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=128, verbose_name='가게이름')),
                ('address', models.CharField(max_length=512, null=True, verbose_name='가게주소')),
                ('foodname', models.CharField(max_length=128, verbose_name='음식이름')),
                ('file', models.FileField(upload_to='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('before eating', '먹기전'), ('eating', '먹는중')], max_length=80, null=True)),
                ('mapx', models.FloatField(default=0, null=True, verbose_name='X좌표')),
                ('mapy', models.FloatField(default=0, null=True, verbose_name='Y좌표')),
                ('author', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
