# Generated by Django 3.1.4 on 2021-01-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='writer',
        ),
    ]
