# Generated by Django 3.1.4 on 2021-01-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('video', '0004_auto_20210130_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.meokda_user', verbose_name='작성자'),
        ),
    ]
