# Generated by Django 3.1.4 on 2021-01-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20210131_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='거리',
        ),
        migrations.AddField(
            model_name='video',
            name='distance',
            field=models.PositiveIntegerField(default=0, verbose_name='거리'),
        ),
        migrations.AlterField(
            model_name='video',
            name='foodname',
            field=models.CharField(max_length=128, verbose_name='음식이름'),
        ),
        migrations.AlterField(
            model_name='video',
            name='restaurant',
            field=models.CharField(max_length=128, verbose_name='가게이름'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('before eating', '먹기전'), ('eating', '먹는중')], max_length=80, null=True),
        ),
    ]
