# Generated by Django 3.1.4 on 2021-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('eating', '먹는중'), ('before eating', '먹기전')], max_length=80, null=True),
        ),
    ]
