# Generated by Django 3.1.4 on 2021-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20210215_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
