# Generated by Django 3.1.4 on 2021-02-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_article_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
