# Generated by Django 3.1.4 on 2021-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20210513_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('eating', '먹는중'), ('before eating', '먹기전')], max_length=80, null=True),
        ),
    ]
