# Generated by Django 3.1.4 on 2021-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20210513_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('before eating', '먹기전'), ('eating', '먹는중')], max_length=80, null=True),
        ),
    ]
