# Generated by Django 3.1.4 on 2021-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20210522_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='distance',
        ),
        migrations.AddField(
            model_name='video',
            name='address',
            field=models.CharField(max_length=512, null=True, verbose_name='가게주소'),
        ),
        migrations.AddField(
            model_name='video',
            name='mapx',
            field=models.IntegerField(default=0, null=True, verbose_name='X좌표'),
        ),
        migrations.AddField(
            model_name='video',
            name='mapy',
            field=models.IntegerField(default=0, null=True, verbose_name='Y좌표'),
        ),
    ]
