# Generated by Django 3.1.4 on 2021-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_auto_20210705_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mapx',
            field=models.FloatField(default=0, null=True, verbose_name='X좌표'),
        ),
        migrations.AlterField(
            model_name='video',
            name='mapy',
            field=models.FloatField(default=0, null=True, verbose_name='Y좌표'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('before eating', '먹기전'), ('eating', '먹는중')], max_length=80, null=True),
        ),
    ]
