# Generated by Django 3.1.4 on 2021-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20210705_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mapx',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, null=True, verbose_name='X좌표'),
        ),
        migrations.AlterField(
            model_name='video',
            name='mapy',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, null=True, verbose_name='Y좌표'),
        ),
    ]
