# Generated by Django 3.1.4 on 2021-01-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meokda_user',
            options={'verbose_name': '먹다_사용자', 'verbose_name_plural': '먹다_사용자'},
        ),
        migrations.AddField(
            model_name='meokda_user',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
