# Generated by Django 3.1.4 on 2021-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_meokda_user_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meokda_user',
            name='userimage',
        ),
        migrations.AddField(
            model_name='meokda_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
