# Generated by Django 3.1.4 on 2021-01-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210102_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meokda_user',
            old_name='registered_dttme',
            new_name='registered_dttm',
        ),
    ]
