# Generated by Django 3.1.4 on 2021-05-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210513_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meokda_user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='nomal_profile.png', null=True, upload_to=''),
        ),
    ]
