# Generated by Django 3.1.4 on 2021-05-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20210515_1826'),
        ('user', '0004_auto_20210514_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='meokda_user',
            name='uservideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='유저비디오'),
        ),
    ]
