# Generated by Django 3.1.4 on 2021-05-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_meokda_user_uservideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meokda_user',
            name='uservideo',
        ),
    ]
