# Generated by Django 3.1.4 on 2021-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_meokda_user_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meokda_user',
            name='user_comment',
            field=models.TextField(blank=True, default='아직 코멘트가 없습니다!', null=True, verbose_name='내용'),
        ),
    ]
