# Generated by Django 3.1.4 on 2021-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
