# Generated by Django 3.1.4 on 2021-01-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210119_2131'),
        ('board', '0002_board_tags'),
    ]

    operations = [
    ]
