# Generated by Django 3.1.4 on 2021-01-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_merge_20210119_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
